name: soda_agent
description: "Soda - AI Car Voice Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.0
  flutter_riverpod: ^2.4.0
  permission_handler: ^11.0.0
  record: ^6.2.0
  flutter_sound: ^9.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
